export enum IplayarrParameter {
    DEBUG = 'DEBUG',
    PORT = 'PORT',
    API_KEY = 'API_KEY',
    ACTIVE_LIMIT = 'ACTIVE_LIMIT',
    DOWNLOAD_DIR = 'DOWNLOAD_DIR',
    COMPLETE_DIR = 'COMPLETE_DIR',
    GET_IPLAYER_EXEC = 'GET_IPLAYER_EXEC',
    ADDITIONAL_IPLAYER_DOWNLOAD_PARAMS = 'ADDITIONAL_IPLAYER_DOWNLOAD_PARAMS',
    SUB_DIR = 'SUB_DIR',
    VIDEO_QUALITY = 'VIDEO_QUALITY',


    SONARR_API_KEY = 'SONARR_API_KEY',
    SONARR_HOST = 'SONARR_HOST',
    SONARR_DOWNLOAD_CLIENT_ID = 'SONARR_DOWNLOAD_CLIENT_ID',
    SONARR_INDEXER_ID = 'SONARR_INDEXER_ID',

    RADARR_API_KEY = 'RADARR_API_KEY',
    RADARR_HOST = 'RADARR_HOST',
    RADARR_DOWNLOAD_CLIENT_ID = 'RADARR_DOWNLOAD_CLIENT_ID',
    RADARR_INDEXER_ID = 'RADARR_INDEXER_ID',

    REFRESH_SCHEDULE = 'REFRESH_SCHEDULE',

    AUTH_USERNAME = 'AUTH_USERNAME',
    AUTH_PASSWORD = 'AUTH_PASSWORD',

    TV_FILENAME_TEMPLATE = 'TV_FILENAME_TEMPLATE',
    MOVIE_FILENAME_TEMPLATE = 'MOVIE_FILENAME_TEMPLATE',
    FALLBACK_FILENAME_SUFFIX = 'FALLBACK_FILENAME_SUFFIX',

    NZB_URL = 'NZB_URL',
    NZB_API_KEY = 'NZB_API_KEY',
    NZB_TYPE = 'NZB_TYPE',
    NZB_USERNAME = 'NZB_USERNAME',
    NZB_PASSWORD = 'NZB_PASSWORD'
}