export enum IplayarrParameter {
    DEBUG = "DEBUG",
    PORT = "PORT",
    API_KEY = "API_KEY",
    ACTIVE_LIMIT = "ACTIVE_LIMIT",
    DOWNLOAD_DIR = "DOWNLOAD_DIR",
    COMPLETE_DIR = "COMPLETE_DIR",
    GET_IPLAYER_EXEC = "GET_IPLAYER_EXEC",
    SUB_DIR = "SUB_DIR",

    SONARR_API_KEY = "SONARR_API_KEY",
    SONARR_HOST = "SONARR_HOST",
    SONARR_DOWNLOAD_CLIENT_ID = "SONARR_DOWNLOAD_CLIENT_ID",
    SONARR_INDEXER_ID = "SONARR_INDEXER_ID",

    RADARR_API_KEY = "RADARR_API_KEY",
    RADARR_HOST = "RADARR_HOST",
    RADARR_DOWNLOAD_CLIENT_ID = "RADARR_DOWNLOAD_CLIENT_ID",
    RADARR_INDEXER_ID = "RADARR_INDEXER_ID",

    REFRESH_SCHEDULE = "REFRESH_SCHEDULE"
}